service: aggregation
app: serverless-slackbot
org: vfn2002

custom:
  SNSArn:
    !ImportValue ${self:provider.stage}-ExtResponseTopicArn
  SNSTopicName:
    !ImportValue ${self:provider.stage}-ExtResponseTopicName

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

functions:
  aggregate:
    handler: handler.aggregate
    events:
      # Using any other methods of intrinsic functions or references
      # does not seem to create the subscription to this ARN.
      # weird af.
      - sns: arn:aws:sns:eu-central-1:600242996258:slack-response-${self:provider.stage}-topic