service: slack
app: serverless-slackbot
org: vfn2002

custom:
  snsTopicArn:
    Ref: SNSTopic

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  iamRoleStatements:
  - Effect: "Allow"
    Resource: "*"
    Action:
      - "sns:Publish"

functions:
  addResponse:
    handler: handler.addResponse
    environment:
      snsTopicArn: ${self:custom.snsTopicArn}
    events:
      - http:
          path: response
          method: post
          integration: lambda

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Slack Response Topic
        TopicName: ${self:service}-response-${self:provider.stage}-topic

  Outputs:
    ResponseTopicArn:
      Value:
        Ref: SNSTopic
      Export:
        Name: ${self:provider.stage}-ExtResponseTopicArn

    ResponseTopicName:
      Value: ${self:service}-response-${self:provider.stage}-topic
      Export:
        Name: ${self:provider.stage}-ExtResponseTopicName