on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - name: npm install
      uses: actions/setup-node
      with: 
        node-version: '12.x'
    - run: npm install
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY }}
